@extends('layouts.backoffice')

@section('js')
  @parent
<!-- amcharts -->
<script type="text/javascript" src="{{ asset('/bower_components/amcharts3/amcharts/amcharts.js') }}" ></script>
<script type="text/javascript" src="{{ asset('/bower_components/amcharts3/amcharts/serial.js') }}" ></script>
<script type="text/javascript" src="{{ asset('/bower_components/amcharts3/amcharts/themes/light.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/aj-charts.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/backoffice.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/backoffice-investors.js') }}"></script>

<script type="text/javascript" src="{{ asset('/bower_components/select2/dist/js/select2.min.js') }}" ></script>
<link rel="stylesheet" href="{{ asset('/bower_components/select2/dist/css/select2.min.css') }}" >

<!-- datepicker -->
<link href="{{ asset('/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.standalone.min.css') }}" rel="stylesheet">



<script type="text/javascript">
    
    $(document).ready(function() {
        // select2

        $('.select2-single').select2({
            // placeholder: "Search here"
        });

        $('input[name="duration_from"]').datepicker({
          format: 'dd-mm-yyyy'
        }).on('changeDate', function (selected) {
          var minDate = new Date(selected.date.valueOf());
          $('input[name="duration_to"]').datepicker('setStartDate', minDate);
        });

        $('input[name="duration_to"]').datepicker({
          format: 'dd-mm-yyyy'
        }).on('changeDate', function (selected) {
          var maxDate = new Date(selected.date.valueOf());
          $('input[name="duration_from"]').datepicker('setEndDate', maxDate);
        });
       
    });



// ---
// generated by coffee-script 1.9.2
</script>

 <script type="text/javascript">

    $(document).ready(function() {
 
      $('input[name="duration_from"]').datepicker({
        format: 'dd-mm-yyyy'
      }).on('changeDate', function (selected) {
        var minDate = new Date(selected.date.valueOf());
        $('input[name="duration_to"]').datepicker('setStartDate', minDate);
      });

      $('input[name="duration_to"]').datepicker({
        format: 'dd-mm-yyyy'
      }).on('changeDate', function (selected) {
        var maxDate = new Date(selected.date.valueOf());
        $('input[name="duration_from"]').datepicker('setEndDate', maxDate);
      });



    });


  </script>
@endsection

@section('css')
<style>
#activitysummarychart {
    width   : 100%;
    height  : 700px;
}                                       
</style>


@endsection


@section('backoffice-content')

<div class="container">
    @php
        echo View::make('includes.breadcrumb')->with([ "breadcrumbs"=>$breadcrumbs])
    @endphp
    <div class="row mt-5 mx-0">
        <div class="col-md-2 bg-white px-0">
            @include('includes.side-menu')
        </div>

        <div class="col-md-10 bg-white border border-gray border-left-0 border-right-0">
            <div class="">
                <h1 class="section-title font-weight-medium text-primary mb-0">Activity Analysis</h1>
 

                <h5 class="mt-2 mb-0">Selection Filters</h5>
                
                <div class="gray-section border bg-gray p-3">
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="bg-lightgray p-3">
                        <div class="form-group">
                            <select name="duration" class="form-control">
                              <option value="">Select Period</option>
                              @foreach($durationType as $durationKey=>$duration)
                                @php
                                    if(isset($requestFilters['duration']) && $requestFilters['duration'] == $durationKey){
                                        $selected = "selected";
                                    } 
                                    elseif(!isset($requestFilters['duration']) && 'lasttwomonth' == $durationKey){
                                        $selected = "selected";
                                    } 
                                    else{
                                        $selected = "";
                                    }
                                @endphp
                                
                                <option value="{{ $durationKey }}" {{ $selected }} >{{ $duration }}</option>
                              @endforeach

                            </select>
                        </div>

                        <p class="text-center mb-2 font-weight-bold">OR</p>
                        
                        <div class="row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <div class="input-group border-bottom">
                                  <input type="text"  placeholder="Select From Date" class="form-control datepicker date_range" name="duration_from" value="{{ (isset($requestFilters['duration_from'])) ? $requestFilters['duration_from'] : '' }}" @if(isset($requestFilters['duration']) && $requestFilters['duration'] != '') disabled @endif>
                                  <div class="input-group-append border-bottom">
                                    <span class="input-group-text border-0 bg-transparent" id="basic-addon2"><i class="fa fa-calendar"></i></span>
                                  </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="input-group border-bottom">
                                  <input type="text"  placeholder="Select To Date" class="form-control datepicker date_range" name="duration_to" value="{{ (isset($requestFilters['duration_to'])) ? $requestFilters['duration_to'] : '' }}" @if(isset($requestFilters['duration']) && $requestFilters['duration'] != '') disabled @endif>
                                  <div class="input-group-append border-bottom">
                                    <span class="input-group-text border-0 bg-transparent" id="basic-addon2"><i class="fa fa-calendar"></i></span>
                                  </div>
                                </div>
                            </div>
                        </div>
                      </div><!-- /bg-lightgray -->

                      <div class="row mt-3">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                          <div class="">
                              <label for="">Activity Groups</label>
                              <select name="activity_group" id="" class="form-control">
                                <option value="">View All groups</option>
                                @foreach($activityGroups as $activityGroup)
                                  <option value="{{ $activityGroup->id }}" @if(isset($requestFilters['activity_group']) && $requestFilters['activity_group'] == $activityGroup->id) selected @endif>{{ $activityGroup->group_name }}</option>
                                @endforeach
                              </select>
                          </div>
                        </div>
                        <div class="col-sm-6 mb-3 mb-sm-0">
                          <div class="">
                              <label for="">Activities</label>
                              <select name="type" id="" class="form-control">
                                <option value="">View All Activity Type</option>
                                @foreach($activityTypes as $activityTypeKey=>$activityType)
                                  <option value="{{ $activityTypeKey }}" @if(isset($requestFilters['type']) && $requestFilters['type'] == $activityTypeKey) selected @endif>{{ $activityType }}</option>
                                @endforeach
                              </select>
                          </div>
                        </div>
                      </div>

                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                          <label for="">Firms</label>
                          <select name="firm" id="firm" class="form-control">
                            <option value="">View All Firms</option>
                            @foreach($firms as $firm)
                              <option value="{{ $firm->id }}" @if(isset($requestFilters['firm']) && $requestFilters['firm'] == $firm->id) selected @endif>{{ $firm->name }}</option>
                            @endforeach
                          </select>
                      </div>

                      <div class="row">
                        <div class="col-sm-6">
                          <div class="form-group">
                              <label for="">Business Proposals/Funds</label>
                              <select name="companies" id="" class="form-control">
                                <option value="">View All Companies</option>
                                @foreach($businessListings as $businessListing)
                                  <option value="{{ $businessListing->id }}" @if(isset($requestFilters['companies']) && $requestFilters['companies'] == $businessListing->id) selected @endif>{{ $businessListing->title }}</option>
                                @endforeach
                              </select>
                          </div>
                        </div>
                        <div class="col-sm-6">
                          <div class="form-group">
                              <label for="">Users</label>
                              <select name="user" id="user" class="form-control" is-visible="true">
                                <option value="">View All Users</option>
                                @foreach($backofficeUsers as $backofficeUser)
                                  <option value="{{ $backofficeUser->id }}" @if(isset($requestFilters['user']) && $requestFilters['user'] == $backofficeUser->id) selected @endif>{{ $backofficeUser->displayName() }}</option>
                                @endforeach
                              </select>
                          </div>
                        </div>
                      </div>

                      <div class="row mt-sm-4 mt-0 d-sm-flex align-items-sm-center">
                        <div class="col-sm-7">
                            <div class="custom-control custom-checkbox"> 
                              <input type="checkbox" checked name="exclude_platform_admin_activity" id="exclude_platform_admin_activity" class="custom-control-input" value="1">
                              <label class="custom-control-label" for="exclude_platform_admin_activity">Exclude platform admin activities</label> 
                            </div> 
                        </div>
                        <div class="col-sm-5">
                          <div class="">
                              <button class="btn btn-primary mr-1 apply-activity-filters">Apply</button>
                              <button class="btn btn-default reset-activity-filters">Reset</button>
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                    <!-- <div class="row mb-3">
                        <div class="col-md-3">
                            <div>
                                <select name="duration" class="form-control">
                                  <option value="">Select Period</option>
                                  @foreach($durationType as $durationKey=>$duration)
                                    @php
                                        if(isset($requestFilters['duration']) && $requestFilters['duration'] == $durationKey){
                                            $selected = "selected";
                                        } 
                                        elseif(!isset($requestFilters['duration']) && 'lasttwomonth' == $durationKey){
                                            $selected = "selected";
                                        } 
                                        else{
                                            $selected = "";
                                        }
                                    @endphp
                                    
                                    <option value="{{ $durationKey }}" {{ $selected }} >{{ $duration }}</option>
                                  @endforeach

                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div>
                              OR
                                <input type="text"  class="form-control datepicker date_range" name="duration_from" value="{{ (isset($requestFilters['duration_from'])) ? $requestFilters['duration_from'] : '' }}" @if(isset($requestFilters['duration']) && $requestFilters['duration'] != '') disabled @endif> -
                                <input type="text"  class="form-control datepicker date_range" name="duration_to" value="{{ (isset($requestFilters['duration_to'])) ? $requestFilters['duration_to'] : '' }}" @if(isset($requestFilters['duration']) && $requestFilters['duration'] != '') disabled @endif>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label for="">Activity Groups</label>
                                <select name="activity_group" id="" class="form-control">
                                  <option value="">View All groups</option>
                                  @foreach($activityGroups as $activityGroup)
                                    <option value="{{ $activityGroup->id }}" @if(isset($requestFilters['activity_group']) && $requestFilters['activity_group'] == $activityGroup->id) selected @endif>{{ $activityGroup->group_name }}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label for="">Activities</label>
                                <select name="type" id="" class="form-control">
                                  <option value="">View All Activity Type</option>
                                  @foreach($activityTypes as $activityTypeKey=>$activityType)
                                    <option value="{{ $activityTypeKey }}" @if(isset($requestFilters['type']) && $requestFilters['type'] == $activityTypeKey) selected @endif>{{ $activityType }}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                         <div class="col-md-3">
                            <div>
                                <label for="">Firms</label>
                                <select name="firm" id="firm" class="form-control">
                                  <option value="">View All Firms</option>
                                  @foreach($firms as $firm)
                                    <option value="{{ $firm->id }}" @if(isset($requestFilters['firm']) && $requestFilters['firm'] == $firm->id) selected @endif>{{ $firm->name }}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div>
                                <label for="">Users</label>
                                <select name="user" id="user" class="form-control" is-visible="true">
                                  <option value="">View All Users</option>
                                  @foreach($backofficeUsers as $backofficeUser)
                                    <option value="{{ $backofficeUser->id }}" @if(isset($requestFilters['user']) && $requestFilters['user'] == $backofficeUser->id) selected @endif>{{ $backofficeUser->displayName() }}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label for="">Business Proposals/Funds</label>
                                <select name="companies" id="" class="form-control">
                                  <option value="">View All Companies</option>
                                  @foreach($businessListings as $businessListing)
                                    <option value="{{ $businessListing->id }}" @if(isset($requestFilters['companies']) && $requestFilters['companies'] == $businessListing->id) selected @endif>{{ $businessListing->title }}</option>
                                  @endforeach

                                </select>

                                
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div>
                             
                                <input type="checkbox" checked name="exclude_platform_admin_activity" id="exclude_platform_admin_activity" class="" value="1"><lable for="exclude_platform_admin_activity">Exclude platform admin activities</lable>

                            </div>
                        </div>
                    </div>
                    <div class="d-sm-flex justify-content-sm-between align-items-sm-center">

                        <div class="mt-3 mt-sm-0">
                            <button class="btn btn-primary mr-1 apply-activity-filters">Apply</button>
                            <button class="btn btn-default reset-activity-filters">Reset</button>
                        </div>
                    </div> -->

                     

                </div>

                
                <div class="tab-pane fade show active" id="add_clients" role="tabpanel">
                    <!-- tabs -->
                    <div class="squareline-tabs mt-3">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link active d-none d-sm-block" data-toggle="tab" href="#activity-summary">Activity Summary</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link d-none d-sm-block" data-toggle="tab" href="#activity-details">Activity Details</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /tabs -->
                    <div class="tab-content">
                        <div class="tab-pane active p-3" id="activity-summary" role="tabpanel">
                             <div class="activity-summary-count"></div>

                            <h4 class="d-none">Activity Summary (<span class="activity-date-from"></span> to <span class="activity-date-to"></span> )</h4>
                            <div id="activitysummarychart"></div>
                        </div>  
                        <div class="tab-pane p-3" id="activity-details" role="tabpanel">
                             <div class="activity-summary-count"></div> 

                             <div class="text-right mt-3 mb-2">
                                <div class="">
                                    <a href="" class="btn btn-primary" data-toggle="modal" data-target="#columnVisibility">Column Visibility</a>    
                                    <a href="javascript:void(0)" class="btn btn-outline-primary download-investor-activity-report" report-type="csv">Download CSV </a>
                                    <a href="javascript:void(0)" class="btn btn-outline-primary download-investor-activity-report" report-type="pdf"> Download PDF</a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table id="datatable-investor-activity" class="table dataFilterTable table-hover table-solid-bg">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th class="w-search">Business Proposals/Funds</th>
                                            <th class="w-search">User</th>
                                            <th class="w-search">User Type</th>
                                            <th class="w-search">Firm Name</th>
                                            <th class="col-visble">GI Code</th>
                                            <th class="col-visble">Email</th>
                                            <th class="col-visble">Telephone</th>
                                            <th class="col-visble">Description</th>
                                            <th class="w-search">Date</th>
                                            <th class="w-search">Activity</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>


                            </div>
                            <!-- activity-details -->
                        </div>  
                    </div>  

                
            </div>
        </div>
    </div>

     <!-- Modal -->
    <div class="modal fade" id="columnVisibility" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Column Visibility</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body m-auto d-block">
            <div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="0" id="ch_io" checked>
                  <label class="custom-control-label" for="ch_io">Logo</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="1" id="ch_mgr" checked>
                  <label class="custom-control-label" for="ch_mgr"> Business Proposals/Funds</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="2" id="ch_ts" checked>
                  <label class="custom-control-label" for="ch_ts">Users</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="3" id="ch_it" checked>
                  <label class="custom-control-label" for="ch_it">User Type</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="4" id="ch_if" >
                  <label class="custom-control-label" for="ch_if">GI Code</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="5" id="ch_tr" >
                  <label class="custom-control-label" for="ch_tr">Email</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="6" id="ch_mi" >
                  <label class="custom-control-label" for="ch_mi">Telephone</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="7" id="ch_amtr" >
                  <label class="custom-control-label" for="ch_amtr">Description</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="8" id="ch_inv" checked>
                  <label class="custom-control-label" for="ch_inv">Date</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input activity-cols" value="9" id="ch_dwn" checked>
                  <label class="custom-control-label" for="ch_dwn">Activity</label>
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            <button type="button" class="btn btn-primary alter-activity-table">Save changes</button>
          </div>
        </div>
      </div>
    </div>

</div>
 
    <style type="text/css">
        #datatable-investors_filter{
            visibility: hidden;
        }
    </style>

    <script type="text/javascript">

     $(document).ready(function() {

       $('input[name="duration_from"]').datepicker({
         format: 'dd-mm-yyyy'
       }).on('changeDate', function (selected) {
         var minDate = new Date(selected.date.valueOf());
         $('input[name="duration_to"]').datepicker('setStartDate', minDate);
       });

       $('input[name="duration_to"]').datepicker({
         format: 'dd-mm-yyyy'
       }).on('changeDate', function (selected) {
         var maxDate = new Date(selected.date.valueOf());
         $('input[name="duration_from"]').datepicker('setEndDate', maxDate);
       });



     });


   </script>

@endsection

